#The chance of pillager armed with a gun.
#Range: 0.0 ~ 1.0
"Armed Chance" = 0.5
#The chance of pillagers will drop their guns on death.
#Range: 0.0 ~ 1.0
"Drop Chance" = 0.3
#Whether bullets ignore damage immunity.
"Ignore Damage Immunity" = false
#Whether the gun has friend fire.
"Friend Fire" = true
#The shooting accuracy of AI; the lower the value, the higher the accuracy.
#Range: 0 ~ 10
"Shooting Accuracy" = 5
#Entities sharing the same tag from this list will be treated as allies.
"Friendly Tag" = []

["Shot Gun"]
	#The chance of shotgun.
	#Range: 0.0 ~ 1.0
	"Shotgun Chance" = 0.1
	#The power of each shotgun shell.
	#Range: 0 ~ 5000
	"Shotgun Power" = 3
	#The number of shotgun shells.
	#Range: 0 ~ 200
	"Shells Number" = 5

[Pistol]
	#The chance of pistol.
	#Range: 0.0 ~ 1.0
	"Pistol Chance" = 0.5
	#The power of pistol bullet.
	#Range: 0 ~ 5000
	"Pistol Power" = 2

["Assault Rifle"]
	#The chance of assault rifle.
	#Range: 0.0 ~ 1.0
	"Assault Rifle Chance" = 0.2
	#The power of assault rifle bullet.
	#Range: 0 ~ 5000
	"Assault Rifle Power" = 5
	#The percentage of assault rifle bullet damage that ignore armor.
	#Range: 0.0 ~ 1.0
	"Assault Rifle Bypass Armor Chance" = 0.25
	#Whether or not the assault rifle will fire automatically. If false, the assault rifle will use the three-round burst mode.
	"Automatic Shooting" = false

["Sniper's Rifle"]
	#The chance of sniper's rifle.
	#Range: 0.0 ~ 1.0
	"Sniper's Rifle Chance" = 0.05
	#The power of sniper's rifle bullet.
	#Range: 0 ~ 5000
	"Sniper's Rifle Power" = 15
	#Sniper Rifle AI Attack Range Multiplier.
	#Range: 0 ~ 5
	"Sniper's Rifle Bonus" = 1
	#The percentage of sniper's rifle bullet damage that ignore armor.
	#Range: 0.0 ~ 1.0
	"Sniper's Rifle Bypass Armor Chance" = 0.7

[Bazooka]
	#The chance of bazooka.
	#Range: 0.0 ~ 1.0
	"Bazooka Chance" = 0.05
	#The explosion level of bazooka rocket.
	#Range: 1 ~ 50
	"Bazooka Explosion Level" = 8
	#Whether the explosion of bazooka rocket will break block.
	"Bazooka Break Block" = false

["Combat - Zombie Survival Kit"]
	#The chance of flamethrower.
	#Range: 0.0 ~ 1.0
	"Flamethrower Chance" = 0.05
	#The chance of flamethrower with fuel canister.
	#Range: 0.0 ~ 1.0
	"Fuel Canister Chance" = 0.8
	#The chance of flamethrower with napalm fuel canister.
	#Range: 0.0 ~ 1.0
	"Napalm Fuel Canister Chance" = 0.1
	#The chance of flamethrower with high temperature fuel canister.
	#Range: 0.0 ~ 1.0
	"High Temperature Fuel Canister Chance" = 0.1

["Combat - Guard Villager & Recruits"]
	#Whether Guard or Recruit will spawn with gun.
	"Villager Spawn With Gun" = true
	#The chance of Guard or Recruit armed with a gun.
	#Range: 0.0 ~ 1.0
	"Villager Armed Chance" = 1.0
	#The chance of shotgun.
	#Range: 0.0 ~ 1.0
	"Villager Shotgun Chance" = 0.2
	#The chance of pistol.
	#Range: 0.0 ~ 1.0
	"Villager Pistol Chance" = 0.5
	#The chance of assault rifle.
	#Range: 0.0 ~ 1.0
	"Villager Assault Rifle Chance" = 0.2
	#The chance of sniper's rifle.
	#Range: 0.0 ~ 1.0
	"Villager Sniper's Rifle Chance" = 0.05
	#The chance of bazooka.
	#Range: 0.0 ~ 1.0
	"Villager Bazooka Chance" = 0.05
	#The chance of flamethrower.
	#Range: 0.0 ~ 1.0
	"Villager Flamethrower Chance" = 0.05

